pull_request_rules:
  - name: backport patches to the stable branch
    conditions:
      - label=backport
    actions:
      backport:
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}
        branches:
          - "5.8"
